name: Spring Boot CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('SBREST/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and package project (skip tests)
        run: |
          cd SBREST
          mvn clean install -DskipTests

      # Optional: if you want to run tests but ignore failures, uncomment below
      # - name: Run tests (ignore failures)
      #   run: |
      #     cd SBREST
      #     mvn test || true
